

server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5430/ordersDB
    username: postgres
    password: mwas
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: ORDER-SERVICE
  config:
    import: configServer:http://localhost:9296
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8585/eureka}